import { jsPDF } from "jspdf";

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const LEFT = 16;
const RIGHT = 16;
const CONTENT_WIDTH = PAGE_WIDTH - LEFT - RIGHT;
const FOOTER_Y = 287;

const cleanText = (value) => {
  let text = String(value ?? "");

  text = text
    .normalize("NFKD")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\u2022/g, "-")
    .replace(/\u00A0/g, " ")
    .replace(/[\u200B-\u200D\uFEFF]/g, "")
    .replace(/[^\x20-\x7E\n\r\t]/g, "")
    .replace(/[ \t]+/g, " ")
    .trim();

  return text.replace(
    /\b(?:[A-Za-z]\s+){3,}[A-Za-z]\b/g,
    (match) => match.replace(/\s+/g, "")
  );
};

const readableLabel = (value) =>
  String(value || "")
    .replaceAll("_", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());

const formatDate = (dateValue) => {
  if (!dateValue) {
    return "Date unavailable";
  }

  return new Intl.DateTimeFormat("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(dateValue));
};

export function generateInterviewPdf({
  interview,
  answers,
  candidateName,
}) {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    putOnlyUsedFonts: true,
    compress: true,
    precision: 16,
  });

  let y = 20;

  const setText = (size = 10, style = "normal", color = [52, 64, 94]) => {
    pdf.setFont("helvetica", style);
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    pdf.setCharSpace(0);
  };

  const drawText = (text, x, currentY, options = {}) => {
    pdf.setCharSpace(0);

    pdf.text(cleanText(text), x, currentY, {
      charSpace: 0,
      baseline: "alphabetic",
      ...options,
    });
  };

  const drawHeader = () => {
    pdf.setFillColor(39, 60, 117);
    pdf.roundedRect(LEFT, 11, 14, 14, 3, 3, "F");

    setText(7, "bold", [255, 255, 255]);
    drawText("PP", LEFT + 3.6, 19.3);

    setText(17, "bold", [39, 60, 117]);
    drawText("PrepPilot", LEFT + 19, 17.3);

    setText(8, "normal", [111, 123, 150]);
    drawText("AI Interview Practice Report", LEFT + 19, 22.3);

    pdf.setDrawColor(225, 230, 241);
    pdf.line(LEFT, 28, PAGE_WIDTH - RIGHT, 28);
  };

  const drawFooter = (pageNumber, totalPages) => {
    pdf.setDrawColor(228, 232, 241);
    pdf.line(LEFT, FOOTER_Y - 5, PAGE_WIDTH - RIGHT, FOOTER_Y - 5);

    setText(7.5, "normal", [133, 143, 165]);
    drawText(
      "Generated by PrepPilot - AI Interview Practice",
      LEFT,
      FOOTER_Y
    );

    drawText(
      `Page ${pageNumber} of ${totalPages}`,
      PAGE_WIDTH - RIGHT,
      FOOTER_Y,
      {
        align: "right",
      }
    );
  };

  const addPage = () => {
    pdf.addPage();
    drawHeader();
    y = 38;
  };

  const ensureSpace = (height) => {
    if (y + height > FOOTER_Y - 9) {
      addPage();
    }
  };

  const writeParagraph = (
    text,
    options = {
      fontSize: 10,
      lineHeight: 5.2,
      color: [92, 105, 136],
    }
  ) => {
    const safeText = cleanText(text);

    if (!safeText) {
      return;
    }

    setText(
      options.fontSize || 10,
      options.style || "normal",
      options.color || [92, 105, 136]
    );

    const lines = pdf.splitTextToSize(safeText, CONTENT_WIDTH);
    const requiredHeight = lines.length * (options.lineHeight || 5.2) + 3;

    ensureSpace(requiredHeight);

    pdf.text(lines, LEFT, y, {
      charSpace: 0,
      lineHeightFactor: 1.18,
    });

    y += requiredHeight;
  };

  const writeSectionTitle = (title) => {
    ensureSpace(12);

    setText(11.5, "bold", [48, 62, 99]);
    drawText(title, LEFT, y);

    y += 3;

    pdf.setDrawColor(216, 223, 239);
    pdf.line(LEFT, y, PAGE_WIDTH - RIGHT, y);

    y += 7;
  };

  const writeBulletList = (items) => {
    const list = Array.isArray(items) ? items : [];

    list.forEach((item) => {
      const text = cleanText(item);

      if (!text) {
        return;
      }

      setText(9.5, "normal", [92, 105, 136]);

      const lines = pdf.splitTextToSize(text, CONTENT_WIDTH - 8);
      const requiredHeight = lines.length * 5 + 3;

      ensureSpace(requiredHeight);

      pdf.setFillColor(83, 111, 200);
      pdf.circle(LEFT + 2, y - 1.2, 1, "F");

      pdf.text(lines, LEFT + 6, y, {
        charSpace: 0,
        lineHeightFactor: 1.17,
      });

      y += requiredHeight;
    });
  };

  const writeScoreRow = (scores = {}) => {
    const entries = Object.entries(scores);

    if (!entries.length) {
      return;
    }

    const boxWidth = CONTENT_WIDTH / Math.min(entries.length, 5);

    ensureSpace(18);

    entries.slice(0, 5).forEach(([key, value], index) => {
      const x = LEFT + index * boxWidth;

      pdf.setFillColor(247, 249, 255);
      pdf.setDrawColor(224, 230, 243);

      pdf.roundedRect(x, y, boxWidth - 3, 15, 2, 2, "FD");

      setText(6.8, "bold", [121, 133, 160]);
      drawText(
        readableLabel(key).toUpperCase(),
        x + (boxWidth - 3) / 2,
        y + 5.3,
        {
          align: "center",
        }
      );

      setText(10.5, "bold", [72, 94, 165]);
      drawText(
        `${value}/10`,
        x + (boxWidth - 3) / 2,
        y + 11.3,
        {
          align: "center",
        }
      );
    });

    y += 21;
  };

  drawHeader();

  setText(8.5, "bold", [98, 117, 173]);
  drawText("INTERVIEW PERFORMANCE REPORT", LEFT, 39);

  setText(20, "bold", [47, 61, 96]);
  drawText(interview.interview_type || "Interview Report", LEFT, 49);

  setText(9.5, "normal", [109, 121, 146]);
  drawText(
    `Prepared for ${candidateName || "Candidate"} | ${formatDate(
      interview.completed_at || interview.created_at
    )}`,
    LEFT,
    56
  );

  pdf.setFillColor(239, 243, 255);
  pdf.roundedRect(LEFT, 65, CONTENT_WIDTH, 25, 4, 4, "F");

  setText(8, "bold", [101, 119, 176]);
  drawText("OVERALL SCORE", LEFT + 8, 74);

  setText(21, "bold", [47, 62, 116]);
  drawText(`${interview.overall_score || 0}/10`, LEFT + 8, 84);

  setText(8, "bold", [101, 119, 176]);
  drawText("INTERVIEW READINESS", LEFT + 78, 74);

  setText(11, "bold", [61, 119, 85]);
  drawText(
    interview.readiness_level || "In progress",
    LEFT + 78,
    83
  );

  y = 101;

  writeSectionTitle("Overall Summary");
  writeParagraph(interview.summary || "No summary available.");

  const report = interview.final_report || {};

  writeSectionTitle("Your Strengths");
  writeBulletList(report.strengths || []);

  writeSectionTitle("Areas to Improve");
  writeBulletList(report.improvement_areas || []);

  writeSectionTitle("Action Plan");
  writeBulletList(report.action_plan || []);

  answers.forEach((item, index) => {
    ensureSpace(20);

    writeSectionTitle(`Question ${index + 1}`);

    setText(10, "bold", [53, 66, 101]);
    writeParagraph(item.question, {
      fontSize: 10,
      style: "bold",
      color: [53, 66, 101],
      lineHeight: 5.4,
    });

    setText(8.5, "bold", [101, 118, 159]);
    drawText("YOUR ANSWER", LEFT, y);
    y += 5;

    writeParagraph(item.user_answer, {
      fontSize: 9.5,
      color: [92, 105, 136],
      lineHeight: 5,
    });

    writeScoreRow(item.scores || {});

    setText(8.5, "bold", [101, 118, 159]);
    drawText("COACH FEEDBACK", LEFT, y);
    y += 5;

    writeParagraph(item.feedback, {
      fontSize: 9.5,
      color: [92, 105, 136],
      lineHeight: 5,
    });

    if (item.improved_answer) {
      setText(8.5, "bold", [67, 126, 87]);
      drawText("IMPROVED ANSWER DIRECTION", LEFT, y);
      y += 5;

      writeParagraph(item.improved_answer, {
        fontSize: 9.5,
        color: [77, 113, 88],
        lineHeight: 5,
      });
    }

    if (Array.isArray(item.evidence) && item.evidence.length > 0) {
      setText(8.5, "bold", [101, 118, 159]);
      drawText("EVIDENCE USED", LEFT, y);
      y += 5;

      writeBulletList(item.evidence);
    }

    if (index < answers.length - 1) {
      y += 3;
    }
  });

  const totalPages = pdf.getNumberOfPages();

  for (let page = 1; page <= totalPages; page += 1) {
    pdf.setPage(page);
    drawFooter(page, totalPages);
  }

  const safeCandidateName = cleanText(candidateName || "Candidate")
    .replace(/\s+/g, "-")
    .toLowerCase();

  pdf.save(
    `PrepPilot-Interview-Report-${safeCandidateName || "candidate"}.pdf`
  );
}